"""
backend/reports/brief_builder.py

Builds a Markdown case brief from AnalysisResult + GraphPayload.

Public API
──────────
build_brief(analysis, graph) -> str
    Render the Jinja2 template with data from the analysis result and graph.
"""
from __future__ import annotations

from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from backend.schemas.analysis import Role
from backend.schemas.graph import GraphPayload
from backend.schemas.result import AnalysisResult

_TEMPLATES_DIR = Path(__file__).parent / "templates"
_BRIEF_TEMPLATE = _TEMPLATES_DIR / "fir_brief.md.j2"


def build_brief(
    analysis: AnalysisResult,
    graph: Optional[GraphPayload] = None,
) -> str:
    """
    Render the FIR brief template from an AnalysisResult and optional GraphPayload.

    Parameters
    ----------
    analysis : AnalysisResult
        Full analytics output from the analysis pipeline.
    graph : GraphPayload, optional
        Resolved graph for the case (used for node/edge tables).

    Returns
    -------
    str — rendered Markdown text.
    """
    try:
        from jinja2 import Environment, FileSystemLoader, select_autoescape
        env = Environment(
            loader=FileSystemLoader(str(_TEMPLATES_DIR)),
            autoescape=select_autoescape(enabled_extensions=()),
            keep_trailing_newline=True,
        )
        template = env.get_template("fir_brief.md.j2")
    except ImportError:
        # Jinja2 not installed — return a minimal plain-text brief
        return _build_plain_brief(analysis, graph)

    # Prepare template context
    nodes_by_type: dict[str, list] = defaultdict(list)
    transfer_edges = []

    if graph:
        for node in graph.nodes:
            nodes_by_type[node.type.value].append(node)
        for edge in graph.edges:
            if edge.type.value == "TRANSFERRED_TO":
                transfer_edges.append(edge)

    context = {
        "case_id": analysis.case_id,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "primary_pattern": analysis.primary_pattern,
        "all_patterns": analysis.all_patterns,
        "roles": [rs.model_dump() for rs in analysis.roles],
        "levels": analysis.levels,
        "totals": analysis.totals.model_dump(),
        "timeline": [ev.model_dump() for ev in analysis.timeline],
        "nodes_by_type": {k: list(v) for k, v in nodes_by_type.items()},
        "transfer_edges": transfer_edges,
        "node_count": len(graph.nodes) if graph else 0,
        "edge_count": len(graph.edges) if graph else 0,
    }

    return template.render(**context)


def _build_plain_brief(
    analysis: AnalysisResult,
    graph: Optional[GraphPayload] = None,
) -> str:
    """
    Fallback plain-text brief when Jinja2 is not available.
    """
    lines = [
        f"# JAAL Case Brief — {analysis.case_id}",
        "",
        "> DISCLAIMER: AI-assisted analysis. Requires verification by the investigating officer.",
        "",
        "## Case Summary",
        f"Case ID: {analysis.case_id}",
    ]

    if analysis.primary_pattern:
        p = analysis.primary_pattern
        lines.append(f"Primary Pattern: {p.type.value} (confidence: {p.confidence:.0%})")

    lines += [
        "",
        "## Timeline",
    ]
    for ev in analysis.timeline:
        lines.append(f"- {ev.ts}: {ev.event}")

    lines += [
        "",
        "## Totals",
        f"Estimated loss: {analysis.totals.loss_inr or '—'} INR",
        f"Victims: {analysis.totals.victims or '—'}",
        f"Mules: {analysis.totals.mules or '—'}",
        "",
        "*Report generated by JAAL. AI-assisted. Requires verification by the Investigating Officer.*",
    ]
    return "\n".join(lines)
